// This file is generated by Astro DB
declare module 'astro:db' {
	export const Users: import("@astrojs/db/runtime").Table<
		"Users",
		{"first_name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"first_name","collection":"Users","primaryKey":false,"optional":false}},"last_name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"last_name","collection":"Users","primaryKey":false,"optional":false}},"email":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"email","collection":"Users","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"Users","primaryKey":false,"optional":false}}}
	>;
}
